Update azure-pipelines.yml

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -1,45 +1,45 @@
-trigger:
-  branches:
-    include:
-      - main
+# trigger:
+#   branches:
+#     include:
+#       - main
 
-pr:
-  branches:
-    include:
-      - main
+# pr:
+#   branches:
+#     include:
+#       - main
 
-pool:
-  vmImage: 'ubuntu-latest'
+# pool:
+#   vmImage: 'ubuntu-latest'
 
-variables:
-  - group: hl_docker_registry  
+# variables:
+#   - group: hl_docker_registry  
 
-jobs:
-- job: ScanModelsInRepo
-  steps:
-  - checkout: self
-    displayName: 'Check out the repository to the runner'
+# jobs:
+# - job: ScanModelsInRepo
+#   steps:
+#   - checkout: self
+#     displayName: 'Check out the repository to the runner'
 
-  - script: |
-      echo "$(HL_CONTAINER_REGISTRY_SECRET)" | docker login quay.io -u "$(HL_CONTAINER_REGISTRY_USER)" --password-stdin
-    displayName: 'Login to quay.io'
+#   - script: |
+#       echo "$(HL_CONTAINER_REGISTRY_SECRET)" | docker login quay.io -u "$(HL_CONTAINER_REGISTRY_USER)" --password-stdin
+#     displayName: 'Login to quay.io'
 
-  - script: |
-      scan_results=$(docker run --rm --entrypoint /modelscan/cli -v $(Build.SourcesDirectory)/Models:/files-to-scan quay.io/hiddenlayer/distro-cli-modelscanner:24.6.1 --input /files-to-scan)
-      echo "##vso[task.setvariable variable=scan_results;isOutput=true]$scan_results"
-    displayName: 'Scan models'
-    name: scan_models
+#   - script: |
+#       scan_results=$(docker run --rm --entrypoint /modelscan/cli -v $(Build.SourcesDirectory)/Models:/files-to-scan quay.io/hiddenlayer/distro-cli-modelscanner:24.6.1 --input /files-to-scan)
+#       echo "##vso[task.setvariable variable=scan_results;isOutput=true]$scan_results"
+#     displayName: 'Scan models'
+#     name: scan_models
 
-  - script: |
-      echo "$(scan_models.scan_results)"
-    displayName: 'Scan results'
+#   - script: |
+#       echo "$(scan_models.scan_results)"
+#     displayName: 'Scan results'
 
-  - script: |
-      if echo "$(scan_models.scan_results)" | grep -q 'MALICIOUS'; then
-        echo 'HiddenLayer ModelScanner detected malicious content'
-        exit 1
-      elif echo "$(scan_models.scan_results)" | grep -q 'SUSPICIOUS'; then
-        echo 'HiddenLayer ModelScanner detected suspicious content'
-        exit 1
-      fi
-    displayName: 'Fail job if detection'
+#   - script: |
+#       if echo "$(scan_models.scan_results)" | grep -q 'MALICIOUS'; then
+#         echo 'HiddenLayer ModelScanner detected malicious content'
+#         exit 1
+#       elif echo "$(scan_models.scan_results)" | grep -q 'SUSPICIOUS'; then
+#         echo 'HiddenLayer ModelScanner detected suspicious content'
+#         exit 1
+#       fi
+#     displayName: 'Fail job if detection'
